#!/usr/bin/env python3
"""Build the single-file page.

Inlines src/styles.css, src/body.html and src/js/*.js (in filename order) into
index.html. Data files in src/data are injected wherever the JS contains the
string literal "@DATA:<filename>".

    python3 tools/build.py                  # writes index.html
    python3 tools/build.py --artifact OUT   # also writes a variant without the
                                            # <!doctype>/<html>/<head>/<body> wrapper
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src"


def read(rel):
    return (SRC / rel).read_text(encoding="utf-8")


def js_bundle():
    parts = []
    for f in sorted((SRC / "js").glob("*.js")):
        parts.append(f"/* ---- {f.name} ---- */\n{f.read_text(encoding='utf-8')}")
    js = "\n".join(parts)

    def inject(m):
        data = (SRC / "data" / m.group(1)).read_text(encoding="utf-8")
        return json.dumps(data, ensure_ascii=False).replace("</", "<\\/")

    return re.sub(r'"@DATA:([\w.-]+)"', inject, js)


def build():
    head = read("head.html").strip()
    css = read("styles.css")
    body = read("body.html").strip()
    js = js_bundle()
    style = f"<style>\n{css}\n</style>"
    script = f"<script>\n\"use strict\";\n{js}\n</script>"
    banner = "<!-- Generated by tools/build.py from src/. Edit the sources, then rebuild. -->"
    page = (
        "<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n"
        "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, viewport-fit=cover\">\n"
        f"{head}\n{style}\n</head>\n<body>\n{banner}\n{body}\n{script}\n</body>\n</html>\n"
    )
    (ROOT / "index.html").write_text(page, encoding="utf-8")
    print(f"index.html: {len(page.encode('utf-8')) / 1024:.0f} KB")

    if "--artifact" in sys.argv:
        out = pathlib.Path(sys.argv[sys.argv.index("--artifact") + 1])
        art_head = head.replace(
            "<title>The AI Stack: From Electrons to Answers</title>", "<title>The AI Stack</title>"
        )
        art = f"{art_head}\n{style}\n{body}\n{script}\n"
        out.write_text(art, encoding="utf-8")
        print(f"{out}: {len(art.encode('utf-8')) / 1024:.0f} KB")


if __name__ == "__main__":
    build()
